[config]
; qianzhui=xkm_server ;摸金迷城无效参数
zhuqu=game1
; fuqu=t2_mjmc_game,t3_mjmc_game,t4_mjmc_game,t5_mjmc_game,t6_mjmc_game,t7_mjmc_game,t8_mjmc_game,t9_mjmc_game,t10_mjmc_game,t11_mjmc_game,t12_mjmc_game,t13_mjmc_game,t14_mjmc_game,t15_mjmc_game,t16_mjmc_game,t17_mjmc_game,t18_mjmc_game,t19_mjmc_game,t20_mjmc_game,t21_mjmc_game,t22_mjmc_game
fuqu=game2

;魔灵修真目标端口
serverPort=4001
serverRemotePort=21001

[MYSQL]
mysqluser=root
mysqlpasswd=root
mysqlhost=127.0.0.1
